spring:
  datasource: 
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sample?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
  //data.jpa.repositories.enabled: true